import { useState } from 'react'
import { toast } from 'sonner'
// Never a native `<input type="date">` — see the note at the top of DateField.
import DateField from './DateField'
import { ChevronDown } from 'lucide-react'
import { useSession } from '../SessionContext'
import { upsertProduct } from '../store'
import { coerceQuantity, UNITS } from '../productUnit'
import { formatMoney, currencyDef } from '../currency'
import { promoEndFromDate, promoEndToDate } from '../promoEnd'
import { hasPromo, promoSummaryParts } from './promoSummary'
import { draftChanged, type ProductDraft } from './productDraft'
import ConfirmDialog from '../components/ConfirmDialog'
import { Button } from '../components/ui/button'
import { Input } from '../components/ui/input'
import { Label } from '../components/ui/label'
import { Textarea } from '../components/ui/textarea'
import { Sheet, SheetContent, SheetHeader, SheetTitle } from '../components/ui/sheet'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '../components/ui/select'
import ImagePicker from './ProductImages'
import OptionGroupsEditor from './OptionGroupsEditor'
import { blankCategory, categoryProblem } from './MenuCategoriesDialog'
import { findCategory } from '../menuGroups'
import {
  optionGroupsFromRow, validateMenuCategories,
  MAX_MENU_CATEGORIES, MENU_CATEGORY_NAME_MAX,
} from '@bitetime/shared'
import type { OptionGroup, MenuCategory } from '@bitetime/shared'

// The picker's "create one" entry. A sentinel rather than a real id: it must not collide with a
// category id, and a UUID never starts with a space.
const NEW_CATEGORY = ' new '

/**
 * Has this product's sale already finished? Read once, when the sheet seeds itself.
 *
 * MODULE SCOPE on purpose. `Date.now()` is impure, and the React Compiler refuses one called from
 * anything it compiles. Outside the component the call is opaque to the compiler and the rule is
 * satisfied honestly rather than silenced.
 *
 * Display-only, so the device clock is an acceptable stand-in for the server's here — unlike the
 * storefront's price quote (#68), this never becomes an order, so a merchant's laptop being a few
 * minutes off makes the hint early or late, never a wrong price.
 */
const promoHasEnded = (promoEnd: unknown): boolean =>
  !!promoEnd && new Date(promoEnd as string).getTime() < Date.now()

// `category_id: ''` is the form's "no category". It becomes NULL on the way out — the column has
// no empty-string state, and the two must not be allowed to diverge into "unfiled" and "filed
// under nothing".
const BLANK = {
  name: '', name_zh: '', descr: '', price: '', unit: 'pcs', unit_quantity: 1, active: true,
  promo_price: '', promo_limit: '', promo_end: '', category_id: '',
}

/**
 * One titled card in the sheet's body. The form used to be a single flat column of eleven
 * labelled inputs, every one full width and every one at the same weight, which is what made it
 * read as a wall. Grouping is the whole fix: a merchant changing a price should not have to
 * re-read the option-group editor to find it.
 */
function FormSection({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="bg-card border-[0.5px] border-border rounded-2xl p-4">
      <h4 className="font-heading text-[11px] font-medium tracking-[0.08em] uppercase text-muted-foreground mb-3">
        {title}
      </h4>
      {children}
    </section>
  )
}

/** A required field's label. The asterisk is the only required/optional marker in the form. */
function RequiredMark() {
  return <span className="text-danger-fg" aria-hidden> *</span>
}

/**
 * Add or edit ONE product.
 *
 * A Sheet rather than a centred dialog, and the same shell as the order drawer: header and
 * footer pinned, only the cards between them scrolling, full width on a phone. Save is reachable
 * without scrolling past the photo picker, which is what a form this tall needs.
 *
 * The sheet owns the draft — the manager owns the list. `sessionId` is what tells the two apart:
 * a fresh id per opening, which seeds the form and, in add mode, doubles as the product's id so
 * photos can upload to Storage before the row exists.
 */
export default function ProductFormSheet({
  open,
  onOpenChange,
  product,
  sessionId,
  products,
  categories,
  categoriesSaving,
  onSaveCategories,
  onSaved,
}: {
  open: boolean
  onOpenChange: (open: boolean) => void
  /** The row being edited, or null to add. */
  product: any | null
  /** Regenerated by the manager on every open; the add-mode draft id. */
  sessionId: string
  /** Every product in the shop — the option editor offers to copy from the others. */
  products: any[]
  categories: MenuCategory[]
  categoriesSaving: boolean
  onSaveCategories: (next: MenuCategory[]) => Promise<boolean>
  onSaved: () => Promise<void>
}) {
  const { t, lang, merchant } = useSession()
  const [form, setForm] = useState<any>(BLANK)
  const [busy, setBusy] = useState(false)
  const [msg, setMsg] = useState('')
  const [images, setImages] = useState<string[]>([])
  // Saved by the product's own upsert, not by a second write — see ADR 0008.
  const [optionGroups, setOptionGroups] = useState<OptionGroup[]>([])
  // The inline "+ New category…" draft. `null` is "not creating one" — an empty string is a
  // merchant who opened it and has not typed yet, and the two are different.
  const [newCategory, setNewCategory] = useState<string | null>(null)
  // Whether the row being seeded has a promo whose end date has already passed. Computed while
  // seeding rather than read from `Date.now()` during render (React Compiler forbids calling an
  // impure function while rendering — the result would also go stale without a re-render).
  const [promoEnded, setPromoEnded] = useState(false)
  // The promo block is closed by default and open for a product that already has one: a live
  // promo must never be hidden behind a disclosure the merchant did not know to open.
  const [promoOpen, setPromoOpen] = useState(false)
  const [seeded, setSeeded] = useState<string | null>(null)
  // What the form held when it opened. `draftChanged` measures against this, and an edit-mode
  // photo change moves it — see `persistImages`.
  const [savedDraft, setSavedDraft] = useState<ProductDraft>(
    () => ({ form: BLANK, images: [], optionGroups: [] }),
  )
  // Open when closing the sheet would throw typed work away.
  const [confirmDiscard, setConfirmDiscard] = useState(false)

  const currency = merchant?.currency
  const symbol = currencyDef(currency).symbol

  // Re-seed when a different opening arrives (adjust-state-during-render, as OrderDetailSheet
  // does): keyed on the manager's session id, so opening the same product twice starts clean and
  // a patch that replaces `product` mid-edit does not throw away what is being typed.
  if (open && sessionId !== seeded) {
    setSeeded(sessionId)
    setMsg('')
    setNewCategory(null)
    setConfirmDiscard(false)
    const seededForm = product
      ? {
          name: product.name ?? '', name_zh: product.name_zh ?? '', descr: product.descr ?? '',
          price: String(product.price ?? ''), unit: product.unit ?? 'pcs',
          unit_quantity: product.unit_quantity ?? 1, active: product.active,
          promo_price: product.promo_price === null || product.promo_price === undefined ? '' : String(product.promo_price),
          promo_limit: product.promo_limit === null || product.promo_limit === undefined ? '' : String(product.promo_limit),
          promo_end: promoEndToDate(product.promo_end),
          // THE STORED VALUE, VERBATIM, dangling id and all. `categoryItems` keeps a dead id
          // selectable, the way `unitItems` keeps a legacy unit selectable, so a rename round-trips
          // byte-identically instead of quietly unfiling the product.
          category_id: product.category_id ?? '',
        }
      : BLANK
    const seededImages: string[] = product ? (product.image_urls ?? []) : []
    const seededGroups = product ? optionGroupsFromRow(product.option_groups) : []
    setForm(seededForm)
    setImages(seededImages)
    setOptionGroups(seededGroups)
    setPromoEnded(product ? promoHasEnded(product.promo_end) : false)
    setPromoOpen(product ? product.promo_price !== null && product.promo_price !== undefined : false)
    // ONE snapshot, built from the very values the form was given. Deriving it separately would
    // let the two drift, and the drift would show up as a warning about a change nobody made.
    setSavedDraft({ form: seededForm, images: seededImages, optionGroups: seededGroups })
  }

  // Closing the sheet — by a press outside, by Escape, or by the X — discards whatever is typed.
  // That is fine for a form nobody touched and not fine for a half-filled one, so a changed draft
  // asks first. Saving does not come through here: `save` calls `onOpenChange` directly, because
  // by then there is nothing to lose.
  const dirty = draftChanged({ form, images, optionGroups }, savedDraft)

  function requestOpenChange(next: boolean) {
    if (!next && dirty) { setConfirmDiscard(true); return }
    onOpenChange(next)
  }

  /**
   * The promo columns, from the three form fields. An empty field is NULL — no promo / no cap / no
   * end date — and `promo_price: 0` is a real promo (a free item), so this tests for '' and never
   * for falsiness.
   *
   * `promo_sold` is deliberately absent: the browser cannot write it (a DB trigger pins it), and it
   * is the backend's counter. The whole-row spread below still carries it back unchanged; the
   * trigger is what makes that harmless.
   */
  function promoFields(f: any) {
    return {
      promo_price: f.promo_price === '' ? null : Number(f.promo_price),
      promo_limit: f.promo_limit === '' ? null : Number(f.promo_limit),
      promo_end: promoEndFromDate(f.promo_end),
    }
  }

  /**
   * Returns a message to show, or null. The DB has the same checks — this is the one with words.
   *
   * The `promo_limit` check runs first and unconditionally (not gated on `promo_price !== ''`): the
   * `min="1" step="1"` on the input is a convenience, not the enforcement, so a limit of 0 must be
   * refused here even for a product with no promo price set at all — otherwise it reaches Postgres's
   * `products_promo_limit_positive` constraint as a raw error.
   */
  function promoProblem(f: any): string | null {
    if (f.promo_limit !== '' && (!Number.isInteger(Number(f.promo_limit)) || Number(f.promo_limit) < 1)) {
      return t('The promo limit must be a whole number of at least 1.', '优惠数量上限必须是不小于 1 的整数。')
    }
    if (f.promo_price === '') return null
    const promo = Number(f.promo_price)
    const price = Number(f.price) || 0
    if (!Number.isFinite(promo) || promo < 0) {
      return t('The promo price must be a number, and not negative.', '优惠价必须是非负数字。')
    }
    if (promo >= price) {
      return t('The promo price must be below the normal price.', '优惠价必须低于原价。')
    }
    return null
  }

  async function save(e: React.FormEvent<HTMLFormElement>) {
    e.preventDefault(); setBusy(true); setMsg('')
    const problem = promoProblem(form)
    if (problem) { setMsg(problem); setBusy(false); return }
    const r = product
      // Spread the original row first so sort / active / etc. survive the upsert.
      ? await upsertProduct({
          ...product, ...form, ...promoFields(form),
          image_urls: images,
          option_groups: optionGroups,
          price: Number(form.price) || 0,
          unit_quantity: coerceQuantity(form.unit_quantity),
          // '' is the form's "no category" and NULL is the column's; the picker's create sentinel
          // is intercepted before it can land here, and this is the belt to that brace — a
          // sentinel written as an id would be a product filed under a category nobody can name.
          category_id: form.category_id && form.category_id !== NEW_CATEGORY ? form.category_id : null,
        })
      : await upsertProduct({
          ...form,
          ...promoFields(form),
          id: sessionId,
          image_urls: images,
          option_groups: optionGroups,
          price: Number(form.price) || 0,
          unit_quantity: coerceQuantity(form.unit_quantity),
          category_id: form.category_id && form.category_id !== NEW_CATEGORY ? form.category_id : null,
          merchant_id: merchant!.id,
        })
    if (r.ok) {
      onOpenChange(false)
      await onSaved()
      toast.success(t('Product saved', '产品已保存'))
    } else {
      const err = r.error
      // `promoProblem` above already catches a promo left above a base price the merchant just
      // lowered in THIS save — it reads `f.price`, which is the price being saved, so `8 >= 7` is
      // refused with words before this ever runs. This branch is a backstop for a DIFFERENT writer:
      // the dashboard form is not the only thing that can touch a `products` row (a script, an
      // admin tool, a direct SQL edit), and `products_promo_below_price` is what stops one of those
      // leaving a promo priced above the item. Postgres's raw constraint string is not something to
      // show a merchant if that ever collides with a live promo here.
      if (err.message.includes('products_promo_below_price')) {
        setMsg(t('The promo price is no longer below the normal price. Lower or clear the promo price first.',
          '优惠价已不低于原价。请先降低或清除优惠价。'))
      } else {
        setMsg(err.message || t('Something went wrong.', '出错了。'))
      }
    }
    setBusy(false)
  }

  async function persistImages(image_urls: string[]) {
    // No promo handling here: `product` IS the stored row, so its promo columns go back unchanged,
    // which the backend's change-based gate lets through on any plan (#145).
    const r = await upsertProduct({ ...product, image_urls })
    if (!r.ok) return
    // This write SAVED the photos, so they become part of the snapshot. Without this the sheet
    // would warn about discarding a change that is already in the database.
    setSavedDraft(d => ({ ...d, images: image_urls }))
    await onSaved()
  }

  /**
   * Create one category from the product form, without leaving it.
   *
   * A SECOND write, and knowingly so: the list lives on the merchant row and the product on its
   * own, so there is no single upsert that could carry both (the arrangement ADR 0008 had for
   * option groups and ADR 0013 gives up here). What that costs is an empty category left behind
   * if the product save then fails — benign, because a category holding nothing renders nothing.
   *
   * Appended, never inserted: array order is display order, and a new section quietly landing in
   * the middle of a menu the merchant arranged is worse than one landing at the end.
   */
  async function createCategory() {
    const name = (newCategory ?? '').trim()
    if (!name) return
    const created = { ...blankCategory(), name }
    const next = [...categories, created]
    const bad = validateMenuCategories(next)
    if (bad) { toast.error(categoryProblem(bad, t)); return }
    if (await onSaveCategories(next)) {
      setForm((f: any) => ({ ...f, category_id: created.id }))
      setNewCategory(null)
    }
  }

  /**
   * What the picker offers. The leading entry is "no category" — the state most products are in
   * and the one a merchant must be able to get back to, which is why it is an option rather than
   * an empty selection.
   *
   * Hidden categories are OFFERED, marked as hidden: a merchant filing a product into a section
   * they have switched off is a legitimate thing to do (arranging next month's menu), and
   * removing the option would leave a product already in one unable to be re-selected.
   */
  const categoryItems = [
    { value: '', label: t('No category', '不分类') },
    // The leading entry keeps a DANGLING id selectable — its category was deleted, and the
    // product still carries the id. Exactly the reason `unitItems` below keeps a legacy unit:
    // dropping it would silently rewrite the column on the next save, which here means a Basic
    // ex-Pro shop being refused an ordinary rename (`categoryChanged` sees null vs the stored id).
    ...(form.category_id && !findCategory(categories, form.category_id)
      ? [{ value: form.category_id as string, label: t('Deleted category', '已删除的分类') }]
      : []),
    ...categories.map(c => ({
      value: c.id,
      label: ((lang === 'zh' && c.name_zh) || c.name)
        + (c.active ? '' : ` · ${t('hidden', '已隐藏')}`),
    })),
    ...(categories.length < MAX_MENU_CATEGORIES
      ? [{ value: NEW_CATEGORY, label: t('+ New category…', '+ 新建分类…') }]
      : []),
  ]

  // `items` feeds the trigger's label lookup and the rendered list from one expression.
  // The leading entry keeps a legacy value (e.g. an old "pc") selectable so existing rows
  // survive — dropping it would silently rewrite a merchant's unit on the next save.
  const unitItems = [
    ...(form.unit && !UNITS.some(u => u.value === form.unit)
      ? [{ value: form.unit as string, label: form.unit as string }]
      : []),
    ...UNITS.map(u => ({ value: u.value, label: t(u.en, u.zh) })),
  ]

  const summary = promoSummaryParts(form, {
    money: n => formatMoney(n, currency),
    date: iso => iso,
    t,
  })

  const sold = product?.promo_sold ?? 0

  return (
    // Dismissable by a press outside, as well as by the X and Escape.
    //
    // The old dialog opted out of this with `disablePointerDismissal`, because the unit Select
    // portals its menu to <body> and an item click read as an outside press that closed the whole
    // form. That is no longer true: with the opt-out gone, choosing a unit, choosing a category
    // and picking a promo end date all leave the sheet open, and only a press on the backdrop
    // closes it. The opt-out was costing a merchant the ordinary way out of a drawer for nothing.
    //
    // All three discard the draft, so all three go through `requestOpenChange`: an untouched
    // form just closes, and a changed one asks first.
    <>
      <Sheet open={open} onOpenChange={requestOpenChange}>
        {/* SheetContent carries `data-[side=right]:w-3/4` and `data-[side=right]:sm:max-w-sm`, and a
            plain utility has one variant against its two — so Tailwind orders the base FIRST and it
            wins. Matching the variant lets tailwind-merge drop the base instead. `gap-0` and
            `overflow-hidden` undo the base popup's `gap-4` and let the body be the only scroller. */}
        <SheetContent
          side="right"
          className="data-[side=right]:w-full data-[side=right]:sm:max-w-[680px] gap-0 overflow-hidden"
        >
          <SheetHeader className="shrink-0 border-b border-border pr-12">
            <SheetTitle className="text-[17px]">
              {product ? t('Edit product', '编辑产品') : t('Add a product', '添加产品')}
            </SheetTitle>
          </SheetHeader>

          <form onSubmit={save} className="flex-1 min-h-0 flex flex-col">
            <div className="flex-1 min-h-0 overflow-y-auto bg-background flex flex-col gap-3 p-3 sm:p-4">
              {msg && (
                <div className="text-[13px] text-ink-700 bg-brand-100 border border-border rounded-lg px-[13px] py-[10px] leading-[1.5]">
                  {msg}
                </div>
              )}

              <FormSection title={t('Details', '详情')}>
                <div className="grid gap-3 sm:grid-cols-2">
                  <div className="flex flex-col gap-[6px] min-w-0">
                    <Label htmlFor="pm-1">{t('Name', '名称')}<RequiredMark /></Label>
                    <Input
                      id="pm-1"
                      variant="compact"
                      value={form.name}
                      onChange={e => setForm({ ...form, name: e.target.value })}
                      required
                      placeholder={t('e.g. Brown Butter Cookie', '如：焦化奶油曲奇')}
                    />
                  </div>
                  <div className="flex flex-col gap-[6px] min-w-0">
                    <Label htmlFor="pm-2">{t('Chinese name', '中文名称')}</Label>
                    <Input
                      id="pm-2"
                      variant="compact"
                      value={form.name_zh}
                      onChange={e => setForm({ ...form, name_zh: e.target.value })}
                      placeholder="e.g. 焦化奶油曲奇"
                    />
                  </div>
                  {/* Up here with the names, not down beside Photos. Which section a product belongs
                      to is part of WHAT IT IS. Identity first, then price, then media. */}
                  <div className="flex flex-col gap-[6px] min-w-0">
                    <Label htmlFor="pm-category">{t('Category', '分类')}</Label>
                    <Select
                      value={form.category_id}
                      onValueChange={v => {
                        // The inline create. Writing the shop's list mid-product-edit is a second,
                        // separate save, so a product save that then fails leaves an empty category
                        // behind — benign, because a category holding nothing renders nothing.
                        if (v === NEW_CATEGORY) { setNewCategory(''); return }
                        setNewCategory(null)
                        setForm({ ...form, category_id: v ?? '' })
                      }}
                      items={categoryItems}
                    >
                      <SelectTrigger id="pm-category" className="bg-background border-border text-[13px]">
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent className="z-modal-popover">
                        {categoryItems.map(c => (
                          <SelectItem key={c.value} value={c.value}>{c.label}</SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                    {newCategory !== null && (
                      <div className="flex gap-2">
                        <Input
                          variant="compact"
                          autoFocus
                          value={newCategory}
                          maxLength={MENU_CATEGORY_NAME_MAX}
                          onChange={e => setNewCategory(e.target.value)}
                          // Enter inside a form submits it, and the product is not what is being
                          // saved here. Create the category instead.
                          onKeyDown={e => { if (e.key === 'Enter') { e.preventDefault(); void createCategory() } }}
                          placeholder={t('New category name', '新分类名称')}
                          aria-label={t('New category name', '新分类名称')}
                        />
                        <Button
                          type="button" size="none"
                          className="rounded-lg px-[14px] text-[13px] whitespace-nowrap"
                          disabled={categoriesSaving || newCategory.trim() === ''}
                          onClick={() => void createCategory()}
                        >{categoriesSaving ? t('Saving…', '保存中…') : t('Create', '创建')}</Button>
                      </div>
                    )}
                    {/* Shown only while the product has no category — the one state the rule is
                        about. It used to sit under the picker at all times, one more always-on line
                        of grey text in a form that had six of them. */}
                    {!form.category_id && (
                      <span className="text-[12px] text-muted-foreground">
                        {t('Listed last on your storefront, without a heading.',
                           '将排在店面最后，且不带标题。')}
                      </span>
                    )}
                  </div>
                  <div className="flex flex-col gap-[6px] min-w-0">
                    <Label htmlFor="pm-3">{t('Description', '描述')}</Label>
                    <Textarea
                      id="pm-3"
                      value={form.descr}
                      onChange={e => setForm({ ...form, descr: e.target.value })}
                      placeholder={t('Short description', '简短描述')}
                      className="bg-background text-[13px] rounded-sm py-[7px] px-2.5 min-h-0"
                    />
                  </div>
                </div>
              </FormSection>

              <FormSection title={t('Price', '价格')}>
                <div className="grid gap-3 sm:grid-cols-2">
                  <div className="flex flex-col gap-[6px] min-w-0">
                    <Label htmlFor="pm-4">{t(`Price (${symbol})`, `价格 (${symbol})`)}<RequiredMark /></Label>
                    <Input
                      id="pm-4"
                      variant="compact"
                      type="number"
                      step="0.01"
                      value={form.price}
                      onChange={e => setForm({ ...form, price: e.target.value })}
                      required
                      placeholder="0.00"
                    />
                  </div>
                  <div className="flex flex-col gap-[6px] min-w-0">
                    <Label htmlFor="pm-5">{t('Sold as', '销售单位')}</Label>
                    <div className="flex gap-2">
                      <Input
                        id="pm-qty"
                        variant="compact"
                        type="number"
                        step="0.01"
                        min="0.01"
                        className="w-20 shrink-0"
                        value={form.unit_quantity}
                        onChange={e => setForm({ ...form, unit_quantity: e.target.value })}
                        aria-label={t('Unit quantity', '单位数量')}
                        placeholder="1"
                      />
                      <Select value={form.unit} onValueChange={v => setForm({ ...form, unit: v ?? form.unit })} items={unitItems}>
                        <SelectTrigger id="pm-5" className="flex-1 min-w-0 bg-background border-border text-[13px]">
                          <SelectValue />
                        </SelectTrigger>
                        {/* z-modal-popover (400) floats above the drawer popup (z-drawer). */}
                        <SelectContent className="z-modal-popover">
                          {unitItems.map(u => (
                            <SelectItem key={u.value} value={u.value}>{u.label}</SelectItem>
                          ))}
                        </SelectContent>
                      </Select>
                    </div>
                  </div>
                </div>

                {/* Three fields and three lines of grey help, always on screen, for something most
                    products never have. Closed it is one row — and one row that still says what the
                    promo IS, so a live promo is never hidden behind a disclosure. */}
                <div className="mt-3 border-t border-border pt-3">
                  <button
                    type="button"
                    aria-expanded={promoOpen}
                    onClick={() => setPromoOpen(o => !o)}
                    className="flex w-full items-center gap-2 rounded-lg px-1 py-1.5 text-left text-[13px] cursor-pointer hover:bg-muted"
                  >
                    <ChevronDown className={`size-4 shrink-0 text-muted-foreground transition-transform ${promoOpen ? '' : '-rotate-90'}`} />
                    <span className="font-medium">
                      {hasPromo(form) ? t('Promo price', '优惠价') : t('Add a promo price', '添加优惠价')}
                    </span>
                    {!promoOpen && summary.length > 0 && (
                      <span className="ml-auto truncate text-[12px] text-muted-foreground">
                        {summary.join(' · ')}
                      </span>
                    )}
                  </button>

                  {promoOpen && (
                    <div className="grid gap-3 pt-3 sm:grid-cols-2">
                      <div className="flex flex-col gap-[6px] min-w-0">
                        <Label htmlFor="pm-promo-price">{t(`Promo price (${symbol})`, `优惠价 (${symbol})`)}</Label>
                        <Input
                          id="pm-promo-price"
                          variant="compact"
                          type="number"
                          step="0.01"
                          value={form.promo_price}
                          onChange={e => setForm({ ...form, promo_price: e.target.value })}
                          placeholder="0.00"
                        />
                      </div>
                      <div className="flex flex-col gap-[6px] min-w-0">
                        <Label htmlFor="pm-promo-limit">{t('Promo limit', '优惠数量上限')}</Label>
                        <Input
                          id="pm-promo-limit"
                          variant="compact"
                          type="number"
                          step="1"
                          min="1"
                          value={form.promo_limit}
                          onChange={e => setForm({ ...form, promo_limit: e.target.value })}
                          placeholder={t('No limit', '不限')}
                        />
                      </div>
                      <div className="flex flex-col gap-[6px] min-w-0 sm:col-span-2">
                        <Label htmlFor="pm-promo-end">{t('Promo ends', '优惠结束日期')}</Label>
                        {/* `clearable`, unlike the voucher expiry: there is no enclosing checkbox here,
                            so this is the ONLY way back to "no end date" — and the native input this
                            replaced had the browser's own clear control. */}
                        <DateField
                          id="pm-promo-end"
                          value={form.promo_end}
                          onChange={iso => setForm({ ...form, promo_end: iso })}
                          tz={merchant?.timezone as string | undefined}
                          t={t}
                          lang={lang}
                          clearable
                          placeholder={t('No end date', '无结束日期')}
                        />
                        <span className="text-[12px] text-muted-foreground">
                          {t('The promo runs to the end of that day.', '优惠持续到当天结束。')}
                        </span>
                      </div>
                      {product && product.promo_price !== null && product.promo_price !== undefined && (() => {
                        // M-1: `promo_sold` can outlive a LOWERED `promo_limit` — sell 8 against a cap
                        // of 10, then drop the cap to 3, and the row is `promo_sold: 8, promo_limit: 3`.
                        // Money is unaffected (`remaining = max(0, 3-8) = 0`, so the promo just ends),
                        // but the raw numbers read as "8 of 3 sold", which looks broken. Clamp the
                        // DISPLAY to the cap and say the promo is finished — the DB row is untouched.
                        const limit = product.promo_limit
                        const capReached = limit != null && sold >= limit
                        const shownSold = limit != null ? Math.min(sold, limit) : sold
                        return (
                          <p className="text-[12px] text-muted-foreground sm:col-span-2">
                            {limit
                              ? t(`${shownSold} of ${limit} sold at the promo price.`,
                                  `已以优惠价售出 ${shownSold} / ${limit} 件。`)
                              : t(`${sold} sold at the promo price.`,
                                  `已以优惠价售出 ${sold} 件。`)}
                            {' '}
                            {t('Changing the promo price starts the count again.', '更改优惠价将重新计数。')}
                            {capReached && (
                              <>
                                {' '}
                                {t('This promo is finished — the cap has been reached.', '此优惠已结束——已达上限。')}
                              </>
                            )}
                            {promoEnded && (
                              <>
                                {' '}
                                {t('This promo has ended.', '此优惠已结束。')}
                              </>
                            )}
                          </p>
                        )
                      })()}
                    </div>
                  )}
                </div>
              </FormSection>

              <FormSection title={t('Photos', '图片')}>
                <ImagePicker
                  merchantId={merchant!.id}
                  productId={product ? product.id : sessionId}
                  value={images}
                  onChange={paths => {
                    setImages(paths as string[])
                    // Edit mode: the row exists, so persist immediately — that way a
                    // removed photo isn't left dangling if the sheet is cancelled.
                    if (product) return persistImages(paths as string[])
                  }}
                  t={t}
                />
              </FormSection>

              <FormSection title={t('Options', '选项')}>
                <OptionGroupsEditor
                  // Keyed on the opening, so each product gets its own editor. `open` is seeded from
                  // `value.length` on MOUNT only, so without this a new product inherited the
                  // expanded editor of whichever product was edited before it.
                  key={sessionId}
                  value={optionGroups}
                  onChange={setOptionGroups}
                  currency={currency}
                  t={t}
                  copyFrom={products
                    .filter(p => p.id !== product?.id
                      && optionGroupsFromRow(p.option_groups).length > 0)
                    .map(p => ({
                      id: p.id,
                      name: (lang === 'zh' && p.name_zh) ? p.name_zh : p.name,
                      groups: optionGroupsFromRow(p.option_groups),
                    }))}
                />
              </FormSection>
            </div>

            <div className="shrink-0 flex items-center justify-between gap-3 border-t border-border bg-card px-4 py-3">
              <div className="flex items-center gap-3 min-w-0">
                <button
                  id="pm-active"
                  type="button"
                  role="switch"
                  aria-checked={form.active}
                  onClick={() => setForm({ ...form, active: !form.active })}
                  className={`relative inline-flex h-6 w-11 shrink-0 items-center rounded-pill transition-colors cursor-pointer ${form.active ? 'bg-primary' : 'bg-border'}`}
                >
                  <span className={`inline-block size-5 rounded-pill bg-white shadow-elev-1 transition-transform ${form.active ? 'translate-x-[22px]' : 'translate-x-0.5'}`} />
                </button>
                <Label htmlFor="pm-active" className="min-w-0 truncate text-[13px]">
                  {form.active ? t('Visible in storefront', '在店面显示') : t('Hidden from customers', '对顾客隐藏')}
                </Label>
              </div>
              {/* `size="none"`, not `md`: every md button is `w-full`, which in a pinned footer
                  eats the row and squeezes the visibility toggle off the left edge. */}
              <Button
                type="submit"
                size="none"
                className="shrink-0 rounded-lg px-[18px] py-[9px] text-sm pointer-coarse:min-h-11"
                disabled={busy}
              >
                {busy ? t('Saving…', '保存中…') : product ? t('Save changes', '保存更改') : t('Add product', '添加产品')}
              </Button>
            </div>
          </form>
        </SheetContent>
      </Sheet>

      {/* Outside the Sheet on purpose: a dialog is z-modal (300) and the sheet z-drawer (200), so
          this paints above without the `z-modal-popover` override the in-form confirms need. */}
      <ConfirmDialog
        open={confirmDiscard}
        onOpenChange={setConfirmDiscard}
        title={product ? t('Discard your changes?', '放弃更改？') : t('Discard this product?', '放弃此产品？')}
        body={product
          ? t('This product has changes you have not saved. If you leave now, they are lost.',
              '此产品有未保存的更改。现在离开将会丢失。')
          : t('You have not saved this product. If you leave now, what you typed is lost.',
              '此产品尚未保存。现在离开将会丢失已填写的内容。')}
        confirmLabel={t('Discard', '放弃')}
        cancelLabel={t('Keep editing', '继续编辑')}
        onConfirm={() => onOpenChange(false)}
      />
    </>
  )
}
