import { useEffect, useState } from 'react'
import { toast } from 'sonner'
import { useSession } from '../SessionContext'
import { createMerchantVoucher, updateMerchantVoucher, fetchVoucherRedemptions } from '../store'
import { currencyDef, formatMoney } from '../currency'
import { fmtDateTime } from '../merchantDate'
import { SkeletonText } from '../components/Loaders'
import { Badge } from '../components/ui/badge'
import {
  BLANK_VOUCHER, voucherToForm, formToRules, voucherDraftChanged, type VoucherForm,
} from './voucherDraft'
import ConfirmDialog from '../components/ConfirmDialog'
import { Button } from '../components/ui/button'
import { Input } from '../components/ui/input'
import { Label } from '../components/ui/label'
import { Checkbox } from '../components/ui/checkbox'
// Never a native `<input type="date">` — see the note at the top of DateField.
import DateField from './DateField'
import { Sheet, SheetContent, SheetHeader, SheetTitle } from '../components/ui/sheet'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '../components/ui/select'
import type { Voucher, VoucherRedemption } from '../types'

// Unambiguous alphabet (no 0/O/1/I) so codes read cleanly aloud
const CODE_ALPHABET = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'
function randomChars(len: number) {
  let out = ''
  for (let i = 0; i < len; i++) out += CODE_ALPHABET[Math.floor(Math.random() * CODE_ALPHABET.length)]
  return out
}
// Per-merchant voucher code: <SLUG-PREFIX>-XXXXX — prefix keeps codes unique across shops
function voucherPrefix(slug: string) {
  const alnum = String(slug ?? '').toUpperCase().replace(/[^A-Z0-9]/g, '')
  return alnum.slice(0, 4) || 'SHOP'
}
function generateVoucherCode(slug: string) {
  return `${voucherPrefix(slug)}-${randomChars(5)}`
}

/**
 * One titled card in the sheet's body — the same shell `ProductFormSheet` uses, so the two
 * drawers read as one dashboard rather than two designs.
 */
function FormSection({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="bg-card border-[0.5px] border-border rounded-2xl p-4">
      <h4 className="font-heading text-[11px] font-medium tracking-[0.08em] uppercase text-muted-foreground mb-3">
        {title}
      </h4>
      {children}
    </section>
  )
}

/** A required field's label. The asterisk is the only required/optional marker in the form. */
function RequiredMark() {
  return <span className="text-danger-fg" aria-hidden> *</span>
}

/**
 * One checkbox that reveals its own inputs.
 *
 * A component rather than four copies because the pattern is the thing being repeated, and
 * because the reveal must be CONDITIONAL RENDER, not a hidden div: a hidden `<input>` still
 * submits, still validates and still takes focus from a keyboard, so an unticked limit would
 * block the form on a value the merchant cannot see.
 */
function Disclosure({ id, checked, onCheckedChange, label, children }: {
  id: string
  checked: boolean
  onCheckedChange: (v: boolean) => void
  label: string
  children: React.ReactNode
}) {
  return (
    <div className="flex flex-col gap-2">
      <div className="flex items-center gap-2">
        <Checkbox id={id} checked={checked} onCheckedChange={v => onCheckedChange(v === true)} />
        <Label htmlFor={id} className="text-[13px] font-normal cursor-pointer">{label}</Label>
      </div>
      {checked && <div className="ml-6 flex flex-col gap-[6px]">{children}</div>}
    </div>
  )
}

/**
 * Add or edit ONE voucher.
 *
 * A Sheet, and the same shell as the product and order drawers: header and footer pinned, only
 * the cards between them scrolling, full width on a phone. The sheet owns the draft — the
 * manager owns the list — and `sessionId` is what tells one opening from the next: a fresh id
 * per opening seeds the form, so opening the same voucher twice starts clean.
 *
 * In edit mode the code is READ-ONLY. It is what the merchant has printed and what customers
 * are holding, and the server ignores one in the body anyway; a merchant who needs a different
 * string deactivates this voucher and creates the next, which is deliberately a new campaign.
 */
export default function VoucherFormSheet({
  open,
  onOpenChange,
  voucher,
  sessionId,
  onSaved,
}: {
  open: boolean
  onOpenChange: (open: boolean) => void
  /** The row being edited, or null to add. */
  voucher: Voucher | null
  /** Regenerated by the manager on every open. */
  sessionId: string
  onSaved: () => Promise<void>
}) {
  const { t, lang, merchant } = useSession()
  const [form, setForm] = useState<VoucherForm>(BLANK_VOUCHER)
  const [busy, setBusy] = useState(false)
  const [seeded, setSeeded] = useState<string | null>(null)
  // What the form held when it opened. `voucherDraftChanged` measures against this.
  const [savedDraft, setSavedDraft] = useState<VoucherForm>(BLANK_VOUCHER)
  // Open when closing the sheet would throw typed work away.
  const [confirmDiscard, setConfirmDiscard] = useState(false)
  // The history card's rows. null = not loaded yet for this opening; the effect below refetches
  // per session id, so reopening the same voucher after a cancellation shows the return.
  const [history, setHistory] = useState<VoucherRedemption[] | null>(null)

  const currency = merchant?.currency
  const symbol = currencyDef(currency).symbol
  const editing = !!voucher

  // Re-seed when a different opening arrives (adjust-state-during-render, as ProductFormSheet
  // does): keyed on the manager's session id.
  if (open && sessionId !== seeded) {
    setSeeded(sessionId)
    setConfirmDiscard(false)
    // A new opening starts with no history until the fetch below lands — cleared HERE, with the
    // rest of the per-opening state, so the effect stays a pure fetch.
    setHistory(null)
    const seededForm = voucher ? voucherToForm(voucher) : BLANK_VOUCHER
    setForm(seededForm)
    setSavedDraft(seededForm)
  }

  // Fetched per opening rather than seeded from the row: the list endpoint carries a COUNT, not
  // the rows, and this is the one screen that wants them.
  const voucherId = voucher?.id as string | undefined
  const merchantId = merchant?.id
  useEffect(() => {
    if (!open || !voucherId || !merchantId) return
    let cancelled = false
    fetchVoucherRedemptions(voucherId, merchantId).then(r => {
      if (!cancelled) setHistory(r.ok ? r.data : [])
    })
    return () => { cancelled = true }
  }, [open, sessionId, voucherId, merchantId])

  const dirty = voucherDraftChanged(form, savedDraft)
  function requestOpenChange(next: boolean) {
    if (!next && dirty) { setConfirmDiscard(true); return }
    onOpenChange(next)
  }

  // Annotated, not inferred, so a typo'd kind is a compile error rather than a voucher that
  // prices to nothing.
  const kindItems: { value: 'percent' | 'fixed'; label: string }[] = [
    { value: 'percent', label: t('Percentage (%)', '百分比 (%)') },
    { value: 'fixed', label: t(`Fixed amount (${symbol})`, `固定金额 (${symbol})`) },
  ]

  async function save(e: React.FormEvent<HTMLFormElement>) {
    e.preventDefault(); setBusy(true)
    const rules = formToRules(form)
    const r = voucher
      ? await updateMerchantVoucher(voucher.id as string, merchant!.id, { ...rules, active: form.active })
      : await createMerchantVoucher({ merchantId: merchant!.id, code: form.code, ...rules })
    setBusy(false)
    if (r.ok) {
      toast.success(voucher ? t('Voucher saved', '优惠券已保存') : t('Voucher created', '优惠券已创建'))
      onOpenChange(false)
      await onSaved()
    } else if (r.error?.code === 'unbounded_voucher') {
      // The one refusal a merchant can reach by ticking boxes, so it gets its own sentence rather
      // than the generic one. Unlimited per customer AND unlimited in total is an unlimited
      // discount for one person.
      toast.error(t(
        'Set a total limit when one customer may use a voucher any number of times.',
        '当一位顾客可无限次使用优惠券时，必须设置总使用次数上限。',
      ))
    } else if (r.error?.code === 'duplicate_code') {
      // On edit this can only mean one thing: the merchant is switching this voucher back on while
      // a second live voucher holds the same code. Say which one has to move.
      toast.error(voucher
        ? t('Another active voucher already uses this code. Deactivate it first.', '另一张启用中的优惠券已使用此优惠码。请先停用它。')
        : t('That code is already in use.', '该优惠码已被使用。'))
    } else {
      toast.error(voucher ? t('Could not save voucher.', '无法保存优惠券。') : t('Could not create voucher.', '无法创建优惠券。'))
    }
  }

  return (
    <>
      <Sheet open={open} onOpenChange={requestOpenChange}>
        {/* The same width override ProductFormSheet carries, for the same reason: the base
            `sm:max-w-sm` is too narrow for a form with a date picker, and matching the variant is
            what lets tailwind-merge drop it. */}
        <SheetContent
          side="right"
          className="data-[side=right]:w-full data-[side=right]:sm:max-w-[560px] gap-0 overflow-hidden"
        >
          <SheetHeader className="shrink-0 border-b border-border pr-12">
            <SheetTitle className="text-[17px]">
              {editing ? t('Edit voucher', '编辑优惠券') : t('Add a voucher', '添加优惠券')}
            </SheetTitle>
          </SheetHeader>

          <form onSubmit={save} className="flex-1 min-h-0 flex flex-col">
            <div className="flex-1 min-h-0 overflow-y-auto bg-background flex flex-col gap-3 p-3 sm:p-4">
              <FormSection title={t('Discount', '折扣')}>
                <div className="flex flex-col gap-3">
                  <div className="flex flex-col gap-[6px]">
                    <Label htmlFor="vm-code">{t('Code', '优惠码')}{!editing && <RequiredMark />}</Label>
                    {editing ? (
                      // Disabled, not read-only, so the field itself says it cannot change — the
                      // not-allowed cursor and the muted fill — rather than a sentence under it.
                      // Why it cannot change is in the sheet's own doc comment.
                      <Input id="vm-code" variant="compact" value={form.code} disabled className="font-medium disabled:pointer-events-auto disabled:cursor-not-allowed" />
                    ) : (
                      <div className="flex gap-2">
                        <Input
                          id="vm-code"
                          variant="compact"
                          className="flex-1"
                          value={form.code}
                          onChange={e => setForm({ ...form, code: e.target.value.toUpperCase() })}
                          required
                          placeholder={t('e.g. SAVE10', '如：SAVE10')}
                        />
                        <Button
                          type="button"
                          variant="outline"
                          size="none"
                          className="shrink-0 rounded-sm px-3 text-[12px] bg-card whitespace-nowrap hover:border-primary hover:text-primary hover:bg-brand-100"
                          onClick={() => setForm({ ...form, code: generateVoucherCode(merchant!.slug) })}
                        >
                          {t('Generate', '生成')}
                        </Button>
                      </div>
                    )}
                  </div>
                  <div className="grid gap-3 sm:grid-cols-2">
                    <div className="flex flex-col gap-[6px] min-w-0">
                      <Label htmlFor="vm-kind">{t('Type', '类型')}</Label>
                      <Select
                        value={form.kind}
                        onValueChange={v => setForm({ ...form, kind: (v as 'percent' | 'fixed' | null) ?? form.kind })}
                        items={kindItems}
                      >
                        <SelectTrigger id="vm-kind" className="w-full bg-background text-[13px]">
                          <SelectValue />
                        </SelectTrigger>
                        <SelectContent>
                          {kindItems.map(i => (
                            <SelectItem key={i.value} value={i.value}>{i.label}</SelectItem>
                          ))}
                        </SelectContent>
                      </Select>
                    </div>
                    <div className="flex flex-col gap-[6px] min-w-0">
                      <Label htmlFor="vm-amount">
                        {form.kind === 'percent' ? t('Percent off', '折扣百分比') : t(`Amount off (${symbol})`, `折扣金额 (${symbol})`)}
                        <RequiredMark />
                      </Label>
                      <Input
                        id="vm-amount"
                        variant="compact"
                        type="number"
                        step={form.kind === 'percent' ? '1' : '0.01'}
                        min="0"
                        value={form.amount}
                        onChange={e => setForm({ ...form, amount: e.target.value })}
                        required
                        placeholder={form.kind === 'percent' ? '10' : '5.00'}
                      />
                    </div>
                  </div>
                </div>
              </FormSection>

              {/* Redemption limits and restrictions, each behind its own checkbox — Stripe's coupon
                  screen. Off by default, so the ordinary voucher above is the whole form. */}
              <FormSection title={t('Limits', '使用限制')}>
                <div className="flex flex-col gap-3">
                  <Disclosure
                    id="vm-limit-total"
                    checked={form.limitTotal}
                    onCheckedChange={v => setForm({ ...form, limitTotal: v })}
                    label={t('Limit the total number of redemptions', '限制总兑换次数')}
                  >
                    <Input
                      id="vm-max" variant="compact" type="number" step="1" min="1"
                      value={form.maxUses}
                      onChange={e => setForm({ ...form, maxUses: e.target.value })}
                      placeholder="100"
                    />
                    {/* Lowering the cap under what is already taken is allowed, and says what it
                        does: the voucher reads as fully used from now on. */}
                    {editing && form.limitTotal && form.maxUses !== '' && Number(form.maxUses) < (voucher?.usedCount ?? 0) && (
                      <p className="text-[12px] text-muted-foreground">
                        {t(
                          `Already redeemed ${voucher?.usedCount ?? 0} times, so this voucher will show as fully used.`,
                          `已兑换 ${voucher?.usedCount ?? 0} 次，此优惠券将显示为已用完。`,
                        )}
                      </p>
                    )}
                  </Disclosure>

                  {/* #241, in the merchant's own words. Unticked is one redemption each, which is
                      what every voucher created before this form does. */}
                  <Disclosure
                    id="vm-limit-per-customer"
                    checked={form.limitPerCustomer}
                    onCheckedChange={v => setForm({ ...form, limitPerCustomer: v })}
                    label={t('Reusable — one customer can use this more than once', '可重复使用 — 同一顾客可多次使用')}
                  >
                    <Label htmlFor="vm-per-customer" className="text-[12px] text-muted-foreground">
                      {t('Times per customer (blank = unlimited)', '每位顾客可用次数（留空 = 不限）')}
                    </Label>
                    <Input
                      id="vm-per-customer" variant="compact" type="number" step="1" min="1"
                      value={form.perCustomerLimit}
                      onChange={e => setForm({ ...form, perCustomerLimit: e.target.value })}
                      placeholder={t('unlimited', '不限')}
                    />
                    {/* The one combination the server refuses, said BEFORE they submit. Unlimited
                        each and unlimited in total is an unlimited discount for one person. */}
                    {form.perCustomerLimit === '' && !form.limitTotal && (
                      <p className="text-[12px] text-destructive">
                        {t('Also set a total limit above.', '请同时设置上方的总次数上限。')}
                      </p>
                    )}
                  </Disclosure>

                  <Disclosure
                    id="vm-limit-expiry"
                    checked={form.limitExpiry}
                    onCheckedChange={v => setForm({ ...form, limitExpiry: v })}
                    label={t('Add an expiry date', '设置到期日期')}
                  >
                    {/* Not `clearable`: the enclosing checkbox already clears this field, and a
                        second way to reach the same state is a second thing to explain. */}
                    <DateField
                      id="vm-expires"
                      value={form.expiresOn}
                      onChange={iso => setForm({ ...form, expiresOn: iso })}
                      tz={merchant?.timezone as string | undefined}
                      t={t}
                      lang={lang}
                    />
                    <p className="text-[12px] text-muted-foreground">
                      {t('The voucher works all day on this date, in your shop’s time.', '优惠券在该日期当天（按店铺时区）全天有效。')}
                    </p>
                  </Disclosure>

                  <Disclosure
                    id="vm-limit-min"
                    checked={form.limitMinOrder}
                    onCheckedChange={v => setForm({ ...form, limitMinOrder: v })}
                    label={t('Require a minimum order', '设置最低消费')}
                  >
                    <Input
                      id="vm-min-order" variant="compact" type="number" step="0.01" min="0"
                      value={form.minOrder}
                      onChange={e => setForm({ ...form, minOrder: e.target.value })}
                      placeholder="50.00"
                    />
                    {/* Says which number, because it is not the one at the bottom of the
                        customer's screen. Counting shipping would move the threshold with the
                        delivery address. */}
                    <p className="text-[12px] text-muted-foreground">
                      {t('Counted on the food subtotal, before delivery and tax.', '按商品小计计算，不含配送费与税费。')}
                    </p>
                  </Disclosure>
                </div>
              </FormSection>

              {/* The history — edit mode only, since a new voucher has none. Every line is a fact
                  about the ORDER the code was spent on; the redeemer's account email is not on the
                  wire (CONTEXT.md → Shop customer). A returned row is a cancelled order (ADR 0023),
                  kept on the list so "was it ever used?" still has a true answer. */}
              {editing && (
                <FormSection title={t('Redemptions', '兑换记录')}>
                  {history === null ? (
                    <SkeletonText lines={2} />
                  ) : history.length === 0 ? (
                    <p className="text-[13px] text-muted-foreground">{t('No redemptions yet.', '尚无兑换记录。')}</p>
                  ) : (
                    <>
                      <p className="text-[12px] text-muted-foreground mb-3">
                        {(() => {
                          const returned = history.filter(h => h.voidedAt).length
                          const live = history.length - returned
                          const used = t(`${live} used`, `已用 ${live} 次`)
                          return returned ? `${used} · ${t(`${returned} returned`, `已退回 ${returned} 次`)}` : used
                        })()}
                      </p>
                      <ul className="flex flex-col divide-y divide-border">
                        {history.map(h => (
                          <li key={h.id} className="flex items-center justify-between gap-3 py-2 first:pt-0 last:pb-0">
                            <div className="min-w-0">
                              {h.orderId ? (
                                <div className="text-[13px] font-medium text-foreground truncate">
                                  {h.orderNumber}
                                  {h.customerName && <span className="font-normal text-muted-foreground"> · {h.customerName}</span>}
                                </div>
                              ) : (
                                // Backfilled from the old `used_by` list: no order, no time.
                                <div className="text-[13px] text-muted-foreground italic">
                                  {t('Earlier redemption · no order record', '早期兑换 · 无订单记录')}
                                </div>
                              )}
                              {h.redeemedAt && (
                                <div className="text-[12px] text-muted-foreground">{fmtDateTime(h.redeemedAt)}</div>
                              )}
                            </div>
                            <div className="flex items-center gap-2 shrink-0">
                              {h.discount != null && (
                                <span className={`text-[13px] whitespace-nowrap ${h.voidedAt ? 'text-muted-foreground line-through' : 'text-foreground'}`}>
                                  −{formatMoney(h.discount, currency)}
                                </span>
                              )}
                              {h.voidedAt && (
                                <Badge variant="outline" className="uppercase tracking-[0.08em]">
                                  {t('Returned', '已退回')}
                                </Badge>
                              )}
                            </div>
                          </li>
                        ))}
                      </ul>
                    </>
                  )}
                </FormSection>
              )}
            </div>

            <div className={`shrink-0 flex items-center gap-3 border-t border-border bg-card px-4 py-3 ${editing ? 'justify-between' : 'justify-end'}`}>
              {/* The same switch the product sheet pins to its footer, for the same state: on the
                  storefront or not. Edit mode only — a brand-new code that starts paused is a code
                  nobody asked for, and the create route does not take the field. */}
              {editing && (
                <div className="flex items-center gap-3 min-w-0">
                  <button
                    id="vm-active"
                    type="button"
                    role="switch"
                    aria-checked={form.active}
                    onClick={() => setForm({ ...form, active: !form.active })}
                    className={`relative inline-flex h-6 w-11 shrink-0 items-center rounded-pill transition-colors cursor-pointer ${form.active ? 'bg-primary' : 'bg-border'}`}
                  >
                    <span className={`inline-block size-5 rounded-pill bg-white shadow-elev-1 transition-transform ${form.active ? 'translate-x-[22px]' : 'translate-x-0.5'}`} />
                  </button>
                  <Label htmlFor="vm-active" className="min-w-0 truncate text-[13px]">
                    {form.active ? t('Active at checkout', '结账时可用') : t('Paused — not redeemable', '已暂停 — 无法兑换')}
                  </Label>
                </div>
              )}
              {/* `size="none"`, not `md`: every md button is `w-full`, which in a pinned footer
                  eats the row. */}
              <Button
                type="submit"
                size="none"
                className="shrink-0 rounded-lg px-[18px] py-[9px] text-sm pointer-coarse:min-h-11"
                disabled={busy}
              >
                {busy ? t('Saving…', '保存中…') : editing ? t('Save changes', '保存更改') : t('Create voucher', '创建优惠券')}
              </Button>
            </div>
          </form>
        </SheetContent>
      </Sheet>

      {/* Outside the Sheet on purpose: a dialog is z-modal (300) and the sheet z-drawer (200), so
          this paints above without an override. */}
      <ConfirmDialog
        open={confirmDiscard}
        onOpenChange={setConfirmDiscard}
        title={editing ? t('Discard your changes?', '放弃更改？') : t('Discard this voucher?', '放弃此优惠券？')}
        body={editing
          ? t('This voucher has changes you have not saved. If you leave now, they are lost.',
              '此优惠券有未保存的更改。现在离开将会丢失。')
          : t('You have not saved this voucher. If you leave now, what you typed is lost.',
              '此优惠券尚未保存。现在离开将会丢失已填写的内容。')}
        confirmLabel={t('Discard', '放弃')}
        cancelLabel={t('Keep editing', '继续编辑')}
        onConfirm={() => onOpenChange(false)}
      />
    </>
  )
}
